Module3 task1
htmlacademy-javascript/1196281-keksobooking-21 pull request #2
Opened 2020-09-26 13:27 UTC by Igo987

Создание массива объектов (объявлений) на основе шаблона, создание DOM-элементов на основе получившихся объектов

2020-09-27 12:46 UTC, Igo987 reviewed
Изменил путь к файлу

2020-09-29 16:13 UTC, iksah requested changes

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +const price = templateAdd.querySelector(`.popup__text--price`).textContent;
Здесь должны быть не значения из шаблона, а "фейковые данные" для отрисовки.  
Для адреса - строка с двумя случайнми числами, для цены - случайное число.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +}
Здесь и выше - значения можно было "захардкодить" (объявить константу TIMES_OUT=[times0, times1, ...]), и выбирать случайное значение из неё.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +const MapPins = document.querySelector(`.map__pin`);
С большой буквы называются только структуры данных и "классы" (до этого доберемся потом). Нужно переименовать в mapPins

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +
Внутри объектов пустые строки вставлять не стоит - кажется, что это два разных объекта, а не один.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +  newAdd.push(newObject);
На каждой итерации у нас будет получаться одинаковый объект. Нужно на каждой итерации получать новые случайные значения.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +      'y': getRandomIntInclusive(130, 630),
address должен совпадать по содержимому с location

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +  const NewPin = pin.cloneNode(true);
тоже - с маленькой буквы.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +  const Image = NewPin.querySelector(`img`);
и здесь тоже нужно с маленькой буквы.
Image - это класс, стркутура данных, а не отдельный экземпляр.
Иначе говоря - есть класс Хлеб, который описывает любой хлеб, какой только есть, и есть конкретная буханкаХлеба, которую можно купить в магазине.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +  newAdd.push(newObject);
Т.е. выше сделать функцию получения случайного элемента из массива, и здесь использовать её для получения нужных значений.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +  MapPin.style.top = massiveAdd[j].location.y + 82 + `px`;
32 и 82 - сейчас это магические числа. Не ясно, что они означают. Нужно вынести их в константы и дать подходящие названия.

2020-09-29 16:13 UTC, iksah commented on js/main.js
> +// то я реализации задачи, без цикла, не вижу(
> как без цикла подставлять номер j-того элемента этого массива?
К элементам массива можно обращаться без цикла.

let arr = [....];
let index = getRandomInt(0, arr.length);
let randomElement = arr[index];

2020-09-29 16:14 UTC, iksah commented on js/main.js
> +  roomsArray = rooms[i].textContent;
https://github.com/htmlacademy-javascript/1196281-keksobooking-21/pull/2#discussion_r496862087

2020-09-30 16:52 UTC, iksah requested changes

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +  return getRandomIntInclusive(0, arr.length - 1);
Можно было бы сразу возвращать элемент массива.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +roomOptions = roomOptionElements[getRandomIndexfromArr(roomOptionElements, getRandomIntInclusive)].textContent;
getRandomIntInclusive здесь не нужен, потому что `getRandomIndexfromArr` использует только первый переданный в неё аргумент.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +  return getRandomIntInclusive(0, arr.length - 1);
let index = ...
return arr[index]

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +function getRandomIndexfromArr(arr) {
При использовании camelCase каждое слово кроме первого пишем с большой буквы. А значит должно быть getRandomIndexFromArr

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +const ArrType = [`palace`, `flat`, `house`, `bungalow`];
Это - константа. Нежно написать название в UPPER_SNAKE_CASE

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +
Здесь строка все ещё не удалена.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +const ArrType = [`palace`, `flat`, `house`, `bungalow`];
Это кстати касается и других констант в файле.
Константа - это значение известное на момент запуска программы. Есть так же "неизменяемые переменные" - переменные, которые вычисляются один раз в процессе исполнения программы.
При этом любая константа - это неизменяемая переменная, но не всякая неизменяемая переменная является константой.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +const ArrType = [`palace`, `flat`, `house`, `bungalow`];
Ну и название arr type - не очень. Не ясно, что это. Если это типы помещения - то это premisesTypes.
Для массивов нужно использвать множественное число, а не добавлять arr / array

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +      'y': getRandomIntInclusive(130, 630),
Нужно сначала определить x и y, а затем использовать их для составления address и заполнения location.
Сейчас в поле address  и в поле location значения получатся разные.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +let roomOptions = {};
Не нужно сначала присваивать roomOptions пустой объект, можно сразу написать
`let roomOptions =  roomOptionElements[getRandomIndexfromArr(roomOptionElements, getRandomIntInclusive)].textContent`  
Опять же, если у нас одно значение - roomsOption. Так же здесь скорее стоит назвать roomsCount, что бы было ясно, что разговор именно о количестве комнат.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +  newAdd.push(newObject);
Не исправлено.
Все ещё генерируем одниковые объекты.
Нужно получать значения внутри этого цикла.
Т.е. не нужно заранеее вычислять поля.
Прямо здесь напиши:
```
{
  rooms: getRandomElement(roomsOptions),
}
```

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +}
Я уже писал, что записывать вычисляемое значение внутри условия - некорректно, потому что оно будет вычисляться каждый раз.
Попробуй добавить в функцию `getRandomIntInclusive` логгирование (например `console.log('getRandomIntInclusive'`) и посмотри, как часто она вызывается. 
Случайное значение нужно вычислить **до** объявления цикла.

2020-09-30 16:52 UTC, iksah commented on js/main.js
> +}
Кроме того, сейчас у тебя эта инструкция всегда возвращает несколько первых элементов списка, что не корректно.
1) Сделай функцию, которая будет возвращать заданное количество случайных элементов из переданного в неё списка `getRandomElements(array, count)`
2) Сделай функцию, которая будет возвращать случайное количество случайных элементов из списка, при этом будет использовать первую функцию. `getSomeRandomElements(array)`

При этом постарайся сделать так, что бы в список не попадали одинаковые элементы.
Затем используй её там, где тебе нужно получить список элементов.

2020-10-04 10:20 UTC, iksah requested changes

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +  let newObject = {
Перед созданием нового объекта определи его адрес.
```
/* адрес */
const valueLocationX = `120`;
const valueLocationY = `500`;
const address = `${valueLocationX}, ${valueLocationY}`;
```

При заполнении локации используй valueLocationX и valueLocationY.
Сделать это нужно внутри цикла, что бы у каждого объукта были  свои адрес и локация.

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +const address = (`location.x:` + `${valueLocationX}` + `,` + `location.y:` + `${valueLocationY}`);
Нужно перенести вычисления внутрь цикла.

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +  return newArr;
Лучше не передавать сюда **newArr** как аргумент, а создавать его здесь.
В текущем варианте вместо `while (i < count)` лучше воспользоваться  `for (let i = 0; i < count; i++)`.

Сейчас мы можем получить в результате работы этой функции одинаковые элементы в результирующем списке.
Решить проблему можно двумя способами:
- Проверять, есть ли такой элемент в результирующем списке, если есть - добавлять, если нет - брать новый. Это не осень оптимальный способ, потому что можно попасть в оченб большой цикл (например, мы хотим получить 19 случайных элементов из 20 - чем ближе мы будем подбираться к концу работы функции, тем чаще будуд попадаться одинаковые элементы). Кроме того, в оригинальном массиве тоже могут быть повторяющиеся элементы, и мы можем упустить такую возможность.
- Сделать копию массива, и удалять из неё элементы массива, которые мы добавили в результирующий массив. Здесь есть свои нюанся, но это намного более предсказуемый и надежный вариант.

В результате должно получиться что то в духе этого:

```
function getRandomElements(arr) {
  let arrCopy = [...app]; // Копируем массив
  let result = [];
  let randomElementCount = getRandomIntInclusive(0, arr.length);
  for (let i = 0; i < randomElementCount; i++) {
    let randomIndex = getRandomIntInclusive(0, arrCopy.length - 1);
    let elementToAdd = arrCopy.splice(randomIndex, 1);
    result.push(elementToAdd);
  }
  return result;
}
```

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +function getRandomIndexFromArr(arr) {
Функция назвается "Получить случайный индекс из массива", но возвращает - случайный элемент. Давай переименуем в `getRandomElement(arr)`

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +const randomFeatures = [];
Не надо создавать здесь этот список. Лучше создавать переменные ближе к месту их испоьзования.

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +const newPhotoArr = [];
Не надо создавать здесь этот список. Лучше создавать переменные ближе к месту их испоьзования.

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +const roomOptionElements = document.querySelector(`#housing-rooms`);
Давай что бы потом не использовать textContent переформируем список прямо здесь:
``` const roomOptions = document.querySelector(`#housing-rooms`).map((el) => el.textContent);```

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +const roomOptionElements = document.querySelector(`#housing-rooms`);
Тоже самое касается `times` и `timesOut`

2020-10-04 10:20 UTC, iksah commented on js/main.js
> +const times = document.querySelector(`#timein`);
Давай что бы было консистентно со вторым массивом назовем `timesIn`

2020-10-06 08:55 UTC, iksah requested changes

2020-10-06 08:55 UTC, iksah commented on js/main.js
> +      'features': getRandomElements(FEATURES, randomFeatures),
```suggestion
      'features': getRandomElements(FEATURES),
```

2020-10-06 08:55 UTC, iksah commented on js/main.js
> +      'photos': getRandomElements(PHOTOS, newPhotoArr),
```suggestion
      'photos': getRandomElements(PHOTOS),
```

2020-10-06 08:55 UTC, iksah commented on js/main.js
> +const timeIn = Array.from(document.querySelectorAll(`#timein`)).map((el) => el.textContent).toString().replace(/ +/g, ` `).trim().split(`\n`);
> ```.toString().replace(/ +/g, ` `).trim().split(`\n`)```

А зачем это? Если нужно изменить содержимое отдельных элементов - это стоит сделать внутри map(...).

2020-10-06 09:43 UTC, merged